Advanced caching part 1
ImageManagerOrg/IO pull request #49
Opened 2021-05-08 13:14 UTC by Qizot

This PR introduces information storing of persisted images with their ttls, etags and last fetch times.

Yet to be done is cache clearing based on those information.

2021-05-08 21:04 UTC, Przemyslaw5 requested changes

2021-05-08 21:04 UTC, Przemyslaw5 commented on src/test/java/com/io/image/manager/models/CacheRecordRepositoryTest.java
> +    }
use convention 
`
//when
//given
//then
`

2021-05-09 16:03 UTC, Qizot commented on src/main/java/com/io/image/manager/models/CacheRecord.java
> +@Entity
I know that, but the H2 had some problems with auto generated `toString` and `hashCode` therefore creating cycling dependency so I removed that on purpose

2021-05-09 16:42 UTC, Przemyslaw5 approved these changes

2021-05-09 18:16 UTC, merged